#! /usr/bin/perl

if($#ARGV < 1)
{
	print "Usage: $0 rootdir destdir\n";
	die;
}

chdir($ARGV[0]);
$destdir = $ARGV[1];
if($destdir =~ /\/$/) {chop($destdir);}

open(HEADER, ">$destdir/textures.h") or die "Can't write to textures.h!";
open(LIST, ">$destdir/texlist.h") or die "Can't write to texlist.h!";
@img = `ls images/*.png`;
chomp(@img);

print "  AUTOH   texlist.h\n";
print LIST "/* This file is automatically generated by gentextures.pl */\n";
print LIST "const char *TEX_LIST[] = {	";
for($x=0;$x<=$#img;$x++)
{
	print LIST "\"$img[$x]\",\\\n				";
}

print LIST "NULL};\n";
print "  AUTOH   textures.h\n";
print HEADER "/* This file is automatically generated by gentextures.pl */\n";
#print HEADER "#ifndef __gl_h_\n";
print HEADER "#include \"SDL_opengl.h\"\n";
#print HEADER "#include \"GL/gl.h\"\n";
#print HEADER "#endif\n\n";
print HEADER "GLuint LoadTexture(const char *filename);\n";
print HEADER "int InitTextures(void);\n";
print HEADER "void QuitTextures(void);\n";
print HEADER "\n#define NUM_TEXTURES ", $#img+1, "\n";
print HEADER "extern GLuint *GLTexture;\n\n";

for($x=0;$x<=$#img;$x++)
{
	$img[$x] =~ s/.*\/(.*)\.png/$1/;
	print HEADER "#define TEX_$img[$x] GLTexture[$x]\n";
}

print HEADER "\nenum texoffset {\n";
for($x=0;$x<$#img;$x++)
{
	print HEADER "\tT_$img[$x],\n";
}
print HEADER "\tT_$img[$#img]};\n";
