/* This file is automatically generated by gensounds.pl */
char *SND_LIST[] = {	"./sounds/cannon1.wav",\
			"./sounds/spnray02.wav",\
			"./sounds/spnray03.wav",\
			"./sounds/wepnsel1.wav",\
			"./sounds/zoomout6.wav",\
			NULL};
