/* This file is automatically generated by gensounds.pl */
#ifndef _MIXER_H_
	#include "SDL_mixer.h"
#endif

void SDLPlaySound(Mix_Chunk *snd);
int InitSounds(void);
void QuitSounds(void);

#define NUM_SOUNDS 5
extern Mix_Chunk **Sounds;

#define SND_cannon1 Sounds[0]
#define SND_spnray02 Sounds[1]
#define SND_spnray03 Sounds[2]
#define SND_wepnsel1 Sounds[3]
#define SND_zoomout6 Sounds[4]
