/* This file is automatically generated by gentextures.pl */
char *TEX_LIST[] = {	"./images/BlueNova.png",\
			"./images/BlueStar.png",\
			"./images/ButtonConfigure.png",\
			"./images/ButtonFight.png",\
			"./images/ButtonQuit.png",\
			"./images/Cloth.png",\
			"./images/EdgeSmoke.png",\
			"./images/Fireball.png",\
			"./images/FlatlandFiery.png",\
			"./images/Lava.png",\
			"./images/Marble2.png",\
			"./images/Marble.png",\
			"./images/Noise.png",\
			"./images/Parque2.png",\
			"./images/Parque.png",\
			"./images/Rain.png",\
			"./images/Slate.png",\
			"./images/Target.png",\
			"./images/Test.png",\
			"./images/Title.png",\
			"./images/Walnut.png",\
			NULL};
