/* This file is automatically generated by gentextures.pl */
#ifndef __gl_h_
	#include "GL/gl.h"
#endif

GLuint LoadTexture(char *filename);
int InitTextures(void);
void QuitTextures(void);

#define NUM_TEXTURES 21
extern GLuint *GLTexture;

#define TEX_BlueNova GLTexture[0]
#define TEX_BlueStar GLTexture[1]
#define TEX_ButtonConfigure GLTexture[2]
#define TEX_ButtonFight GLTexture[3]
#define TEX_ButtonQuit GLTexture[4]
#define TEX_Cloth GLTexture[5]
#define TEX_EdgeSmoke GLTexture[6]
#define TEX_Fireball GLTexture[7]
#define TEX_FlatlandFiery GLTexture[8]
#define TEX_Lava GLTexture[9]
#define TEX_Marble2 GLTexture[10]
#define TEX_Marble GLTexture[11]
#define TEX_Noise GLTexture[12]
#define TEX_Parque2 GLTexture[13]
#define TEX_Parque GLTexture[14]
#define TEX_Rain GLTexture[15]
#define TEX_Slate GLTexture[16]
#define TEX_Target GLTexture[17]
#define TEX_Test GLTexture[18]
#define TEX_Title GLTexture[19]
#define TEX_Walnut GLTexture[20]
